### ISSUE TITLE
参加申込み用サイトをPeatix上に設けました

### ISSUE THREAD

**Issue by kenjiorita39** [WLO-RaspiClub/20170622_IFTTT#1]
参加申込み用サイトをPeatix上に設けました。
http://raspi170622.peatix.com

交流用Facebookグループページ　https://www.facebook.com/groups/WLORaspberryPiClub/　
においても、イベントページを設けました。
https://www.facebook.com/events/2007425842814430/
＊グループページは現在、非公開設定。将来、公開設定に変更予定

事務局　おりた

**Comment by utaani** [comment]
ありがとうございます。Peatixページのリンクを記載しました。
