### ISSUE TITLE
シェルスクリプトpolling.shde

### ISSUE THREAD

**Issue by kenjiorita39** [WLO-RaspiClub/20170622_IFTTT#3]
*上記のシェルスクリプトの中に、curl -X POST https://maker.ifttt.com/trigger/button/with/key/__Your__IFTTT__TRIGGER__KEY__ が必要？

**Comment by utaani** [comment]
polling.shはGoogle DriveにアクセスするものなのでIFTTTのキーは不要です。

**Comment by kenjiorita39** [comment]
コメントありがとうございます。私が勘違いしている気がしますが、Google Driveにアクセスするトリガーはpolling.shの中のどれになりますか？
